source "https://rubygems.org"

gem "middleman", "~>3.0.13"
gem "middleman-livereload"
gem "middleman-smusher"
gem "middleman-gh-pages"
gem "compass-rgbapng"
gem "compass-css-arrow"
gem "rb-fsevent", "~> 0.9.0"
gem "rake", ">= 0.9.2.2"
gem "roo", "1.11.1"
